export enum Positions {
  USER_NOVALID = 'USER_NOVALID',
  USER_VALID = 'USER_VALID',
  USER_STANDARD = 'USER_STANDARD',
  USER_PREMIUM = 'USER_PREMIUM',
  USER_GOLD = 'USER_GOLD',
  USER_ADMIN = 'USER_ADMIN',
  USER_ADMIN2 = 'USER_ADMIN2'
}
