export enum Status {
  CANCELED = 'CANCELED',
  NOVALIDATED = 'NOVALIDATED',
  VALIDATED = 'VALIDATED',
  PAYMENTINPROGRESS = 'PAYMENTINPROGRESS',
  PAID = 'PAID',
  REFUSEDPAYMENT = 'REFUSEDPAYMENT',
  REFUSEDCREDITPAYMENT = 'REFUSEDCREDITPAYMENT',
  INPREPARATION = 'INPREPARATION',
  INDELIVERY = 'INDELIVERY',
  DELIVERED = 'DELIVERED'
}
